// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: justtest.proto

package collector.grpc;

public interface CoverageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.CoverageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string uuid = 1;</code>
   */
  String getUuid();
  /**
   * <code>optional string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();

  /**
   * <code>optional int32 spanId = 2;</code>
   */
  int getSpanId();

  /**
   * <code>optional string service = 3;</code>
   */
  String getService();
  /**
   * <code>optional string service = 3;</code>
   */
  com.google.protobuf.ByteString
      getServiceBytes();

  /**
   * <code>optional string data = 20;</code>
   */
  String getData();
  /**
   * <code>optional string data = 20;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
