// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: justtest.proto

package collector.grpc;

public final class myProto {
  private myProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_CoverageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_CoverageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_StateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_StateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protocol_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protocol_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016justtest.proto\022\010protocol\"N\n\017CoverageRe" +
      "quest\022\014\n\004uuid\030\001 \001(\t\022\016\n\006spanId\030\002 \001(\005\022\017\n\007s" +
      "ervice\030\003 \001(\t\022\014\n\004data\030\024 \001(\t\"[\n\014StateReque" +
      "st\022\014\n\004uuid\030\001 \001(\t\022\016\n\006spanId\030\002 \001(\005\022\016\n\006meth" +
      "od\030\003 \001(\t\022\017\n\007service\030\004 \001(\t\022\014\n\004data\030\024 \001(\t\"" +
      "\"\n\017ResponseMessage\022\017\n\007message\030\001 \001(\t2\236\001\n\016" +
      "MessageService\022H\n\016uploadCoverage\022\031.proto" +
      "col.CoverageRequest\032\031.protocol.ResponseM" +
      "essage\"\000\022B\n\013uploadState\022\026.protocol.State" +
      "Request\032\031.protocol.ResponseMessage\"\000B \n\016",
      "collector.grpcB\007myProtoP\001\242\002\002PXb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protocol_CoverageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protocol_CoverageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_CoverageRequest_descriptor,
        new String[] { "Uuid", "SpanId", "Service", "Data", });
    internal_static_protocol_StateRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protocol_StateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_StateRequest_descriptor,
        new String[] { "Uuid", "SpanId", "Method", "Service", "Data", });
    internal_static_protocol_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protocol_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protocol_ResponseMessage_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
