// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: justtest.proto

package collector.grpc;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protocol.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>optional string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
