apiVersion: v1
kind: Service
metadata:
  name: ts-gateway-service
spec:
  selector:
    app: ts-gateway  # 这应该与 ts-gateway-service Pod 的标签匹配
  ports:
  - protocol: TCP
    port: 80  # 服务对外暴露的端口
    targetPort: 8080  # Pod 内的目标端口，根据实际情况调整
